language: android
jdk: oraclejdk8
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - COMPILE_SDK_VERSION=28
    - BUILD_TOOLS_VERSION=28.0.3
    - EMULATOR_API=22
    - ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
    - tools
    - platform-tools
    - tools # to update to the newest
    - build-tools-${BUILD_TOOLS_VERSION}
    - android-${COMPILE_SDK_VERSION}
    - android-${EMULATOR_API}
    - extra-android-m2repository
    - sys-img-${ABI}-android-${EMULATOR_API}

before_script:
  - echo no | android create avd --force -n test -t android-${EMULATOR_API} --abi ${ABI}
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew test connectedAndroidTest

after_success:
  - if [[ ! -z $TRAVIS_TAG ]]; then
      export SDK_VERSION=${TRAVIS_TAG:1} && ./gradlew install bintray;
    fi
